import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="light" lang="en">
      <body>
        <div className="bg-gray-300 h-20 flex justify-between items-center px-16">
          <Link href="/">
            <div className="font-bold text-xl">MOVIECRITIC</div>
          </Link>
          <div className=" flex gap-5">
            <Link href="/addmovies">
              <button className="border-2 border-indigo-300 bg-white text-indigo-600 px-4 py-2 rounded-md">
                Add new movie
              </button>
            </Link>
            <Link href="/addreviews">
              <button className="border-2 border-gray-300 bg-indigo-600 text-white px-4 py-2 rounded-md">
                Add new review
              </button>
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
